### ISSUE TITLE
autoclicker poorly randomized or not randomized at all

### ISSUE THREAD

**Issue by BrandowLucas** [decryller/wraith#5]
the autoclicker doesn't take 10s to flag on karhu for: Autoclicker (I) - no randomization

I also tested on coldpvp and got banned in 2 fights using it.

**Comment by decryller** [comment]
Autoclicker is kind of poorly randomized, but it is randomized. It's safe to use unless you go to kinda high CPS (15+). Originally, I tested thoroughly 14 CPS on anticheat-test, on multiple anticheats, with no flags for extended periods of time (except on anticheats that would also flag ~10 CPS human clicking).
On Karhu, I tested:
|CPS|Time|Notes|
|----|----|----|
|13 CPS|A minute and a half|no flagging|
|14 CPS|About 50 seconds|`Autoclicker (C) - Low Outliers`|
|15 CPS|About 40 seconds|`Autoclicker (C) - Low Outliers`|
|17 CPS|About 8 seconds|`Autoclicker (I) - No Randomization`|
|19 CPS|About 5 seconds|`Autoclicker (I) - No Randomization`|

Unless you're using really high CPS, I don't see a reason to worry about `Autoclicker (I)`, just use lower CPS. 
In regards to `Autoclicker (C)`, I will test and modify the autoclicker to hopefully completely eradicate them.
If you're still experiencing `Autoclicker (I)` while using low CPS, please comment on this issue with the CPS count you're getting flagged on.
